<?php

	$number = "002";
	$problem = "Even Fibonacci numbers";
	$description = '<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</p>'.
			'<p style="text-align:center">1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>'.
			'<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>';

	include("../../template.php");

	function calculate() {

		$doNotExceed = 4000000;

		$fib = [1,2,3];

		$maxFib = 3;

		$sum = 2;

		while ( $maxFib < $doNotExceed ) {

			$maxFib = $fib[ count($fib)-1 ] + $fib[ count($fib)-2 ];

			if ( $maxFib < $doNotExceed ) {

				array_push( $fib , $maxFib );

				if ( $maxFib % 2 === 0 ) {
					$sum += $maxFib;
				}

			}

		}

		return $sum;

	}

?>
